#!/bin/bash

read -p "Enter name of the container: " CONTAINER_NAME
read -p "Enter technology to use    : " TECH

#install and configure
apt-get update && apt-get install lxc
cat >> /etc/fstab <<EOL
cgrouip         /sys/fs/cgroup  cgroup  defaults        0       0
EOL
#mount /sys/fs/cgroup
mount -a

#create container
lxc-create -t ${TECH} -n ${CONTAINER_NAME}

#start container and login
lxc-start -n ${CONTAINER_NAME} --daemon
